Attempt to fix macOS compiler version error in CI.
The following error was encountered using macOS-latest in ci.yml:

ERROR: Invalid setting '17' is not a valid 'settings.compiler.version' value.

This macOS-latest version apparently refers to macOS-15 in the GitHub runner
images collection:

https://github.com/actions/runner-images

This supposedly provides Clang/LLVM 18.1.8 via Homebrew, or 16.0.0 otherwise,
but maybe it really provides 17.0.

Presumably, the earlier macOS image will provide the appropriate compiler and
thus defeat this error.

Signed-off-by: Paul Boddie <paul@boddie.org.uk>